[project]
name = "llm-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "docker>=7.1.0",
    "huggingface-hub>=1.16.1",
    "ipykernel==6.*",
    "jupyter>=1.1.1",   # the notebook environment where we'll write and run code
    "minsearch>=0.0.11",    # a simple in-memory search engine for indexing and searching text
    "onnxruntime>=1.27.0",
    "openai>=2.38.0",   # the OpenAI API client for calling the LLM
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.2", # to load API keys from a .env file
    "requests>=2.34.2",             # to fetch the FAQ dataset from the internet
    "sentence-transformers>=5.5.1",
    "sqlitesearch>=0.0.5",
    "toyaikit>=0.0.11",
]
